name: Tests

on:
  - push
  - pull_request

jobs:
  test-py36:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e py36

  test-py37:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e py37

  test-py11:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e py311

  test-py313:
    runs-on: ubuntu-latest
    container:
      image: python:3.13
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - run: tox -e py313

  test-emacs:
    strategy:
      matrix:
        emacs_version: [24.3, 26, 28, 30]
    uses: ./.github/workflows/tests-emacs.yml
    with:
      emacs_version: ${{ matrix.emacs_version }}
